### ISSUE TITLE
10분이 넘는 곡은 길이가 제대로 표시되지 않습니다.

### ISSUE THREAD

**Issue by T-Lee-6948** [ghj1214kr/hatsune#2]
![emphasis](https://user-images.githubusercontent.com/86287384/220521990-2b82ac16-f0e3-4495-8713-39cd0448b81b.png)
10분이 넘는 곡은 길이가 1... 으로만 나오네요.

**Comment by ghj1214kr** [comment]
이슈 남겨주셔서 감사합니다.
해당 부분 고쳐서 올려두었습니다.
https://github.com/ghj1214kr/hatsune/releases/tag/0.3.1
